### ISSUE TITLE
Any chance you can make a docker recipe for this? 

### ISSUE THREAD

**Issue by regulatre** [falling-sky/source#122]
I would like to propose the project be dockerized so mirror sites can be spun up with a single command.

**Comment by jfesler** [comment]
While I like the idea, I don't the time available for that investment.

If someone else wants to work on it, there is this outline of what needs to happen.

* Docker image needs to have several apps in it.     https://github.com/falling-sky/source/wiki
* Docker image needs to figure out what IPv4 and two IPv6 address to use.
* Docker image needs some form of prep after install
  * Identifies domain or subdomain name to launch the product with (such as test-ipv6.example.com)
  * Identifies the IPv4 and IPv6 addresses (plural)
  * Configures iptables for IPv6 https://github.com/falling-sky/source/wiki/InstallPMTUD
  * Configures DNS to listen on IPv4 and IPv6 addresses
  * Configures DNS for several zones relating to the sub domain  https://github.com/falling-sky/source/wiki/InstallDNS
  * Provides required DNS Zones to the operator to install on the operator's primary name servers.  Perhaps this can be DNS slaved using AXFR ; but the operator still has to configure this.  
  * Configures Apache to answer on IPv4 and IPv6, with virtualhost set up for both.  Perhaps as the default domain (might be easiest for a dedicated docker image).  
  * Does the initial rsync over anonymous rsync, with automatically trusting the ssh key https://github.com/falling-sky/source/wiki/InstallContent
  * Configures the falling-sky configuration file based on prior given information. https://github.com/falling-sky/source/wiki/InstallProjectConfigFile
  * If this docker image is to include statistics, then include mysql, configure mysql for localhost, and set up cron.  https://github.com/falling-sky/source/wiki/InstallCharts
* After prep, starts the instance up.
* After starting, directs user to validate.  https://github.com/falling-sky/source/wiki/Validation
* After validation, directs user to consider running an official public instance.   https://github.com/falling-sky/source/wiki/BecomeAnOfficialMirror

I'm pretty sure this covers a lot of it, but I easily could have missed a step.

I know that building a mirror, I can do it in about an hour, if the lag isn't terrible.  I've done enough of them though so that's a very biased single hour.  I could burn an entire vacation trying to get spun up on Docker, and trying to tackle the above stuff - and still not adequately cover everything.  Not only that, but it would restrict who can run this stuff to those who can run Docker.

I'm not saying it can't happen; I am saying it probably won't be me; at least not in the next year.  Not unless I take an unpaid sabbatical from a paying job.

**Comment by jas-** [comment]
Here is a [docker template](https://github.com/marriott-library/Automated-CI-Service/blob/master/docker-templates/www/apache/Dockerfile). Here are some [tools](https://github.com/marriott-library/Automated-CI-Service/tree/master/docker-templates/common); shell scripts which can be used to customize the container environment.

**Comment by jfesler** [comment]
Thank you.  That should be helpful if anyone wants to tackle this work as a project.  
The main challenge will be to handle site-specific configuration magically.

Specifically, each unique instance will need for input:
  - domain name to use for site  (i.e., test-ipv6.example.com)
  - IPv4 address
  - IPv6 address #1  (for basic testing)
  - IPv6 address #2  (for MTU testing)
  - iptables NFQUEUE number (probably 1280 unless more than once instance on a host)

Each unique instance will need to generate as output,
  - Main DNS zone
  - V6NS1 zone
  - ip6tables configuration data for IPv6 address #2 

Once started, the operator will still need to get the DNS data to their primary DNS servers; as well as incorporate the firewall rules on the parent host.  (Unless, of course, Docker can manage per-instance ip6tables rules).

Once all this work is done, what is still missing is a way to keep the mirror up to date.  rsync *can* be used for that (and overwrite /var/www/ using a per-instance docker instance of cron).  Alternately, one has to work out how to get the latest docker image, apply the previous settings to the new image, stop the old image, start the new image.  Or, handle the case of multiple instances running at once, despite conflicts with NFQUEUE (ip6tables).

**Comment by jfesler** [comment]
If anyone is serious about wanting to make this happen, I'll give them guidance.  And I'll take pull requests.  Ideally the best thing would be a standalone project repo that grabs the latest published version, builds the docker image, and publishes it (Without the other build time dependencies here).

I'm still having a hard time imaging it is worth the time effort for this.  Just how many people would actually run mirrors if it were docker, but wouldn't otherwise?  How much of this is just wishing to cut down the 1 hour setup to .. I'm still guessing at least 30 minutes, once you factor in firewalls and dns and testing.

**Comment by jfesler** [comment]
I am thinking more about this.

Building a docker image - with all the prerequisites for serving this site - also assumes responsibility for security of those components.  Of staying up to date.  And most importantly, somehow coercing mirror operators to constantly update their docker images.

This includes bind9, apache, php, glibc (groan), netfilter, rsync, cron, etc. The number of things required is actually staggering - and every additional requirement just increases the frequency of needing to push out (and have people install) updates that are outside their normal security update flow.

Not doing docker: mirror operators don't treat it like an appliance.  The smart ones, manage their VMs like anything else they own (for better or worse).  There is no implied security contract beyond the falling-sky components directly.

Now, we *could* have the container be self-updating.  

Today, mirror operators only sync static serving assets via cron; they aren't syncing over binaries. They don't need to trust me to their servers; especially if they skip the php bits that track stats and the comment form.  It can be totally locked down.   Moving to a model where mirror operators effectively become part of my botnet, that's a different story involving a lot more trust.  If it were me in their shoes, I would stop participating.

I'm marking this closed, wont fix.  I'll leave the thread unlocked  - if there is adequate conversation that can change my mind on this, we can reopen the issue, and look for volunteers.

**Comment by jfesler** [comment]
Last, if I was going to ask people to permit self-updating executables on their mirrors.. 

.. I'd probably redo it all in Go.  Where I can very *easily* integrate and enforce the multiple types of services.  HTTP serving is easy.  HTTP2 serving, will soon be easy.  DNS serving, easy.  The only thing that would not be built-in would be the kernel models needed, and the dependency on rsync for *efficient* frequent delta updates.   Setup would be "grab the binary, or build the binary; install one config file".  The config file would have the IP addresses (plural) and the base domain name.    The admin would then have their primary DNS server, slave what is needed from the go binary..  with little room for error.

The primary reason for Go would be ease of integration.   Once we had *that* - simply putting a docker wrapper around that would be trivial.  And not include half an OS.
