### ISSUE TITLE
Will there be proxy detect？

### ISSUE THREAD

**Issue by dixyes** [falling-sky/source#131]
I'm using shadowsocks as a proxy
My IPv4 will show as my proxy server adress
In fact that‘s not my "IPv4 address on the public Internet"
Maybe we need a proxy detection ?

So, why can't I mark this "issue" as "discuss"

**Comment by jfesler** [comment]
Your proxy server does not pass an HTTP header to indicate that it is proxying.  In particular, it does not pas "Via:".  

Do you have any recommendations (or requests) for other ways to identify proxies?

**Comment by jfesler** [comment]
I do look for HTTP "Via" lines; and if seen, report that the user is using a proxy. This is due to some companies, some schools, etc will use transparent HTTP proxies, for content filtering.  This is done at a much smaller (and much more local) scale than GFW.  However, it is sometimes not obvious to a person visiting that they are using a proxy.  Reporting this proxy is much more important in this case.

When you went out of your way to set up a proxy server, it is assumed that you must realize that you're getting the proxy server's address. 

 Given the name "shadowsocks" I don't think we can ever expect it to add HTTP headers; socks4a and socks5 don't work that way.   That said, if you can suggest a technical way for the browser to detect this; or for the server to see it in the HTTP session.. then I'm open to suggestions.  

PS: Thank you for the huge amount of work you have been putting in, especially these most recent days, with translations.  :+1:
