### ISSUE TITLE
test-ipv6.com and mirrors reachable by IPv6?

### ISSUE THREAD

**Issue by grzchr15** [falling-sky/source#137]
Currently the website http://test-ipv6.com and its mirrors are IP4 reachable. An then there are the IPv6 tests.

But what if i start on a IPv6 only network. Maybe with DNS64/NAT64 or JOOL https://www.jool.mx/en/index.html

How could we create a test site here?

**Comment by jfesler** [comment]
http://test-ipv6.com/faq.html

Q: Why is this web site reachable via IPv4 only?

You're right, there are no AAAA records, intentionally. A percentage of users are unable to browse sites that are dual-stack. If the users can't connect, then they can't be told they have a problem. This is a big problem facing content providers today; of which, I work at one for my $dayjob. As such, the main test page requires IPv4 (either native or translated).

At some point, when the percentage of "broken" users has gone significantly down, I'll consider making test-ipv6.com dual-stack. At least check, May 2013, we still see 0.5% broken visiting test-ipv6.com. And we still want them to understand their situation.

Q: How do I test my IPv6-only host

If you ask that question, chances are you don't need this site. However, if you really want to, visit http://ipv6.test-ipv6.com with your IPv6-only host.

Q: What do you mean by broken?

A percentage of users today have IPv6 enabled, but are either using a public tunnel that is currently giving poor performance; or otherwise have a route that is installed but broken or suboptimal. However, because they have a route at all, in many cases the address selection algorithm of RFC3484 will pick using it, and trying to use this broken route. It can take towards 75+ seconds before the browser gives up!

From the perspective of a user with these conditions, a web site offering both A and AAAA DNS records (ie, "dual stack") will appear to time out; and the user will move on to another site that offers a similar product. This is the quandary content providers have.

If we detect that you will have problems reaching dual-stack web sites, we recommend you see the [Broken User FAQ](http://test-ipv6.com/broken.html). It provides several steps to try and identify your root cause for being broken; and barring that, what you can do to disable IPv6 until your ISP offers native IPv6 connectivity.

Q: Why did your stats say you already have IPv6-only users?
They went to http://ipv6.test-ipv6.com .

**Comment by jfesler** [comment]
Over the last 60 days,  0.31% of the visiting users had *broken* IPv6 (detectably broken, causing timeouts for dual-stack sites).   This is compared with the 600 day average of 0.37%.

http://test-ipv6.com/stats.html

**Comment by jfesler** [comment]
Please let me know if this satisfies your question, so I can mark this as resolved.

**Comment by jfesler** [comment]
Considering this resolved.
