### ISSUE TITLE
Remove powerdns reference for  aaaa-additional-processing

### ISSUE THREAD

**Issue by jfesler** [falling-sky/source#148]
Mitchell K reports in:

> Hello Jason -
> 
> /faq_v6ns_bad.html.en_US offers the following suggestion:
> 
> >> PowerDNS: Enable aaaa-additional-processing and configure query-local-address6 in your recursor.conf. Restart powerdns.
>
>
>It seems PowerDNS has removed aaaa-additional-processing directive [0]. They closed the issue [1] with a note that "nobody has reported actual problems" from its missing functionality. Was your recommendation to enable this flag based on any real world benefits? Any idea if missing this functionality can cause issues?
>
>I have not yet had time to test bind's functionality. Thank you for your input!
>
> - - Mitchell
>
>[0] https://doc.powerdns.com/md/recursor/settings/#aaaa-additional-processing
>[1] https://github.com/PowerDNS/pdns/issues/1448

**Comment by mdkuch** [comment]
Thank you, Jason.

Since the directive's removal in PowerDNS Recursor version 3.6.0, it seems proper to remove the recommendation from Falling-Sky's documentation.

Setting the _aaaa-additional-processing_ flag to _yes_ has been included in many pdns Recursor recipes. I'm not surprised that the suggestion was also made here. I appreciate you taking the time to dig through your notes to determine why it was originally included. My curiosity was peaked when I learned of its removal from pdns. I wonder what, if any, real world use that pdns functionality enabled.

 \- - Mitchell
