### ISSUE TITLE
Ubuntu 18.04

### ISSUE THREAD

**Issue by tobbe-eklov** [falling-sky/source#169]
Hello, for some weeks ago I upgraded my server to Ubuntu 18.04 and after that the falling-sky-dyngraphs-csv.pl stopped working. It's go 1.10.1 now and the req says 1.6.
Anyone have a workaround?

/Tobbe

**Comment by jfesler** [comment]
You do not need go, if you're not building fsbuilder.  If you *are* using rebuilder, then go 1.10 is fine.  I haven't tested 1.11.   This is totally unrelated to any perl problem you're having.

What errors are you getting when you run falling-sky-dyngraphs-csv.pl ? 
Have you tried reinstalling any missing perl modules?

I'd rewrite it in go, but.. I'm currently very limited on what I can do with open source right now.  So, fixing the perl problems are the way to go.

**Comment by tobbe-eklov** [comment]
Ok, I don't get any errors at all. It's only empty dates after the upgrade. And the .csv files hasn't been updated since the upgrade

.csv

2018-08-16,6,,3,14,,,,1
2018-08-17,7,4,2,11,1,,,
Output vith -v
Process:  2018-08-18 00:00:00  to 2018-08-18 23:59:59
.........................
insert into daily_summary (datestamp,total,tokens) values (?,?,?); (2018-08-18, 7, IPv4 only)
insert into daily_summary (datestamp,total,tokens) values (?,?,?); (2018-08-18, 11, Dual Stack - IPv6 Preferred)
insert into daily_summary (datestamp,total,tokens) values (?,?,?); (2018-08-18, 1, Broken DS)
insert into daily_summary (datestamp,total,tokens) values (?,?,?); (2018-08-18, 4, IPv6 only)
insert into daily_summary (datestamp,total,tokens) values (?,?,?); (2018-08-18, 2, Dual Stack - IPv4 Preferred)
Process:  2018-08-19 00:00:00  to 2018-08-19 23:59:59

Process:  2018-08-20 00:00:00  to 2018-08-20 23:59:59

Process:  2018-08-21 00:00:00  to 2018-08-21 23:59:59

Process:  2018-08-22 00:00:00  to 2018-08-22 23:59:59

**Comment by jfesler** [comment]
I don't have a solution, since I don't see an error message.

It seems that it does access the database correctly, as it is identifying values to store into the daily summaries.

if you use perl at all, you might find the perl debugger (perl -d) helpful.  Verify what path the output csv is writing to.   

If you want me to look at your system, then (for whatever account the cron job runs as) give me access to your host. my ssh public key is:
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5EQbAnfZN73ZQPHV1rB9RSVgoh53ZOvlgHk0AfkVbUzisUEKyGjgji8T6UhNyl3edb3fXHJt5HlaDPvo5k8AEgukeXRCHwbycNRz+aSmISNpElrtWuIyv/pzxfQOoSr1a8ynVua8Q1/jLIN40O5TReyV0qPSW8exk8XXyGBYtEoSyk73VHDqlRWPD862E6WLOxuFnLNxqXYSDtFHRRf6yyYBABHMwIdRuQw6CLtIqdWktYgLxfhcON4+WWLuFiTaC6pQeqBFPW45/6riWy0IFwytUil2yJbK7ohPUF7Na0Jwg/6sK1zzjRZUgq/UVV+5vyLlbfPLuaCAZyi6IdRh6+jqPprjHQwaXZYvfUWx9mMKUC1FaSetGFFGNuq1S/TXErS5HH0aoOG6T48I4SeyeHQDlfTYp90lv8oVy0PFzqnkDhIoY2J2s/ErWnyhZfkixyfOdsXkUjUF+UuiSuy4awzAhX648zO37JZ8ISEWTTUMderBUte+l2ROX48IAkZzdMx1sRCeIf+qv1C1pj92guBzQCYZgHTeglYzfYCMm3EnrXd+7qIwOnnLjFOBfx3/gqWAsWWWCOXF25G0JVPTDjbG02+tfIUDGoNy+wHkqvH0wqcYrygx1c6gD8eKdlpPXHfnqAT+NIJzqxok3/HfuIt7/2ylcqlyuykRrtoUWxw== jfesler@Jasons-MacBook.local-2016
```

Append that into ~username/.ssh/authorized_keys .

Contact me at jfesler@test-ipv6.com with hostname and any other special info you feel is relevant.
Note it can take me some time to look at this due to keeping this work far away from my day job.

**Comment by jfesler** [comment]
For those following:  missing php modules after an upgrade.
