### ISSUE TITLE
Statistics not updated

### ISSUE THREAD

**Issue by tobbe-eklov** [falling-sky/source#187]
Hello, my stats is'nt updated and I can't find out why. Can't find any logs that indicates any errors.
Any idea anyone?

<img width="659" alt="Screenshot 2021-08-20 at 19 32 30" src="https://user-images.githubusercontent.com/1199228/130272009-71b2fee2-6b77-42c9-9f31-7319a295421f.png">

/Tobbe

**Comment by jfesler** [comment]
Perhaps a perl upgrade broke things.
Have you tried running the script, looking for errors?

**Comment by jfesler** [comment]
https://github.com/falling-sky/source/wiki/InstallCharts

**Comment by tobbe-eklov** [comment]
Hello, when I run the script it says nothing and I have got the lates extras from github but there is no change.

**Comment by jfesler** [comment]
Alas, this is not really much for me to go on.

Exactly how did you run it?   Did you use 2>/dev/null?  if so, run without it, so that errors are not hidden.

Did the CSV file get updated? 
 - if no: then the script is not working, and it should be producing some form of error.
 - if yes, but still stale data: then something is wrong when people visit your site, and the stats are posted.


I suspect the latter. When I visit your site, I see:

```
(Survey posting failed; the above information is accurate, but not recorded.) /survey.php?x&&a=ok,182&aaaa=ok,900&ds4=bad,725&ds6=ok,725&ipv4=skipped,0&ipv6=skipped,0&v6ns=bad,723&dsmtu=ok,1032&v6mtu=ok,770&tokens=dualstack:ipv6_preferred,tls_beta,v6ns:bad&rand=630940972&ip4=a29&ip6=a29&load=test-ipv6.se&ip6subtype=&callback=?
```

Please check your apache web server log, PHP log, CGI log (whatever's used for your particular instance).  Something about /survey.php? is failing.  Chances are you did an OS upgrade, and some PHP modules are missing.

**Comment by tobbe-eklov** [comment]
I think I have found the problem now, thanks! ( But I don't now how to fix it.... )
It's the site/graphdata.csv that don't get updated and I get "Uncaught Error: Call to undefined function get_magic_quotes_gpc()" in the log.
PHP is 8.0.8 in Ubuntu 20.04.

**Comment by tobbe-eklov** [comment]
I tried to downgrade my php version but I have other webbs on this server that must use PHP 8, puhhh!

**Comment by jfesler** [comment]
I'll put a try wrapper around it. Seems like it should no longer be used; but I gotta keep it for older php installs. 
The try wrapper should suppress any failure to call that function.

**Comment by jfesler** [comment]
survey.php changes. please let me know if we can close this issue.
