### ISSUE TITLE
Move "Other IPv6 Sites" tab to a new link

### ISSUE THREAD

**Issue by saudiqbal** [falling-sky/source#202]
Going to test-ipv6 website runs extra connections to all the mirror sites which is a waste of bandwidth and the website keeps loading until all the mirrors are verified. The mirrors link on the top is good enough when clicked therefore it would be nice to remove the Other IPv6 Sites tab.

**Comment by jfesler** [comment]
The intent of that, is to work through as much of the list as possible while you're looking at other tabs.  Humans observing the results, won't see any delays due to the "other sites" loading.  Their score, IP, and ISP info is shown as soon as it is known.

Can you be more specific about the harm this is causing?

If the issue is something like "takes longer to run with phantomJS" that's .. less of a concern for me.

As to "waste", can you quantify that into an actual cost?

**Comment by saudiqbal** [comment]
My opinion is that the site is making unnecessary connections to different servers all over the world and wasting bandwidth and server resources when the user is only concerned with running the IPv6 test. It should be run the test and be done with it.

**Comment by jfesler** [comment]
I've received your feedback; however, I have no plans to change it.
That connection matrix has actually been instrumental in solving lots of carrier troubles, by effectively crowdsourcing getting the failures reported to the carriers.  It has done a /lot/ of good for the Internet.

I understand you feel differently.

Perhaps IPv6-test.com is better for you.
